language: node_js # specify your language
node_js: # specify options for your language
- '0.10'



script:
- ssh fi4034@rmvm045 'cd data/yocto-proemion-bsp/scripts && ./bsp.sh -f k -d canlink-mobile-7037'

notifications: # set notification options 
  hipchat: vogbboHEVJLT1U8oGiZm6rrdB4l9la76VHiOfRh6@3926556
   # on_success: [always|never|change]
   #on_failure: [always|never|change]
 
